name: mybinder-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyterlab
  - nodejs
  - pyyaml
  - pillow
  - tensorflow
  - keras
  - networkx
  - pulp
